[WIP][8.0][IMP][account_voucher_withholding] Exportación a SICORE
ingadhoc/account-payment pull request #17
Opened 2016-10-25 20:59 UTC by ivantodorovich

Implementación de un Wizard para exportar las retenciones de ganancias a SICORE.

--

Es todavía un WIP, pero ya funcional. 
Favor de probar y sugerir cambios donde sea necesario.

- [ ] Los filtros de fechas y compañia están siendo ignorados (a modo testing). Falta agregarlos al domain.
- [ ] Sugerir rango de fechas por defecto (quincena anterior a la actual)
- [ ] Faltan traducciones

--

**Notas:**

Para que funcione, es necesario configurar el SICORE con estos parámetros de importación:
![sin titulo](https://cloud.githubusercontent.com/assets/1914185/19703846/bffdeecc-9adb-11e6-9789-ed4444950c74.png)

Además, se debe configurar el código de impuestos según la tabla de AFIP
![sin titulo2](https://cloud.githubusercontent.com/assets/1914185/19703910/0a7d8836-9adc-11e6-8400-fd8b97af2e48.png)

2016-10-25 21:53 UTC, ivantodorovich commented
Me faltarían las traducciones.. pero no tengo idea de cómo hacerlas. 
¿Me indicarían cómo?

2016-10-26 00:49 UTC, jjscarafia requested changes

2016-10-26 00:49 UTC, jjscarafia commented on account_voucher_withholding/views/account_withholding_view.xml
> -        <menuitem action="action_account_voucher_withholding" id="menu_account_voucher_withholding" parent="account.menu_finance_bank_and_cash" sequence="11"/>
Por la misma razón que te puse en el punto 3 (para tratar de no modificar a clientes actuales), dejaría el menú actual de retenciones y, tal como haces, agregaría el asitente de exportación en periodic (en este caso no haría falta el menú padre "menu_account_withholding"

2016-10-26 00:49 UTC, jjscarafia commented on account_voucher_withholding/wizard/account_withholding_sicore_wizard.py
> +    company_id = fields.Many2one('res.company', 'Company')
Para mantenerlo a la "odoo way" habría que definir la cia del usuario con "default=lambda self: self.env.user.company_id", aunque entiendo que en tu uso desde la cia padre lo vas a tener que cambiar cada vez. Veo que no lo hiciste obligatorio por lo cual permitis pedir este reporte para todas lass cias, de alguna manera no sería correcto pero entiendo que te va a ser práctico, si preferís dejalo así...

2016-10-26 00:54 UTC, ivantodorovich commented on account_voucher_withholding/wizard/account_withholding_sicore_wizard.py
> +    company_id = fields.Many2one('res.company', 'Company')
En realidad no fue intencional, sinceramente no tenía conocimientos del _odoo way_.
No me molestaría, porque puedo cambiar el default desde mi instancia.
Y lo de hacerlo obligatorio también me parece bien.
Mañana hago los cambios.

2016-10-26 01:08 UTC, ivantodorovich commented on account_voucher_withholding/views/account_withholding_view.xml
> -        <menuitem action="action_account_voucher_withholding" id="menu_account_voucher_withholding" parent="account.menu_finance_bank_and_cash" sequence="11"/>
:thinking:  No encuentro el punto 3 en los comentarios. Pero,

Teniendo la posibilidad de Exportar el archivo a SICORE, el menú de "Comprobantes de Retenciones" casi que nunca se utilizaría. Te lo digo como usuario.

Incluso aquellos que prefieran consultarlas a mano, el hecho de preguntarse a dónde se movió el menú los guiaría hasta la existencia de esta nueva funcionalidad, que de lo contrario podría pasar desapercibida y desaprovechada.

Además, en pos del orden, "Comprobantes de Retenciones" tiene muchísimo más sentido dentro de "Procesamiento periódico" que dentro de "Bancos y efectivo".

¿No sería mejor ofrecer una notificación del cambio a los clientes actuales, en lugar de sacrificar el orden coherente de los menúes?

2016-10-26 01:39 UTC, ivantodorovich commented
@jjscarafia tomando en cuenta tus comentarios, se me ocurre:

- [ ] Dejar el menú Comprobantes de Retenciones donde estaba 
(TODO: borrarlo en alguna próxima versión)
- [ ] Agregar dos nuevos menúes en Procesamiento periódico > Retenciones, llamados Retenciones Sufridas y Retenciones Aplicadas.
- [ ] Ocultar el campo `tax_withholding_type` del wizard. (Usaría siempre el por defecto: payment, es decir, "Retenciones Aplicadas"

2016-10-26 02:01 UTC, jjscarafia commented on account_voucher_withholding/views/account_withholding_view.xml
> -        <menuitem action="action_account_voucher_withholding" id="menu_account_voucher_withholding" parent="account.menu_finance_bank_and_cash" sequence="11"/>
Mirá, no estoy 100% seguro, pero entiendo que retenciones de IIBB y drei, por ejemplo, se liquidan de otra manera distinta, por ejemplo en el consejo creo que liquidan una a una (en esos casos). Como lo vez? Teniendo en cuenta que no es solo para retenciones SICORE?

2016-10-26 02:02 UTC, jjscarafia commented on account_voucher_withholding/wizard/account_withholding_sicore_wizard.py
> +    company_id = fields.Many2one('res.company', 'Company')
Bárbaro, fijate tranquilo esto, la verdad, no estoy seguro que tiene prioridad, si el valor por defecto del campo o el valor por defecto definido por el usuario, habría que probarlo...

2016-10-26 02:04 UTC, ivantodorovich commented on account_voucher_withholding/views/account_withholding_view.xml
> -        <menuitem action="action_account_voucher_withholding" id="menu_account_voucher_withholding" parent="account.menu_finance_bank_and_cash" sequence="11"/>
Tenés razón, no tenía en cuenta esas otras retenciones.

Que te parece esto? https://github.com/ingadhoc/account-payment/pull/17#issuecomment-256226830

> · Dejar el menú Comprobantes de Retenciones donde estaba y tal cual estaba (TODO: borrarlo en alguna próxima versión) Particularmente, yo podría ocultarlo de mi instancia para no verlo.
> · Agregar dos nuevos menúes en Procesamiento periódico > Retenciones, llamados Retenciones Sufridas y Retenciones Aplicadas. Autoexplicadas por su nombre. Tiene sentido separarlas, ya que a la hora de consultarlas (por cualquier sea el motivo) se las quiere ver por separado.

2016-10-26 02:07 UTC, jjscarafia commented
No viste el punto 3 porque quedé a medio escribir lo que te estaba poniendo y me fuí a cenar, copio acá abajo lo que iba escribiendo:
Ivan, muy buen laburo y desde ya muchas gracias por el PR y la prolijidad del mismo. Ojalá ubiese colaboraciones así con la localización.
La verdad es que estamos con poco tiempo para testear funcionalmente el módulo y no estamos interiorizados con el requerimiento de exportación, así que mi propuesta es la siguiente:
1. Vemos de hacer algunas adaptaciones
2. Aprobamos el PR y los disponibilizamos
3. Básicamente el único que lo usaría (por lo menos cliente de adhoc) sería vos, si detectas cosas a corregir las vas haciendo y prometo aceptar los PR lo más pronto posible.

Te parece ok?

Respecto a los cambios, la idea es:
- [ ] Sobre la versión del módulo. Cambiamos el último dígito si solo un restart (o nada) es requerido, el dígito anterior si un update es requerido, y el ante-anterior si requiere alguna cuestión manual (correr un init o hacer algún cambio manual), cuestión, en este PR solo haría falta cambiar el penúltimo, sería "8.0.1.10.0".
- [ ] Modificaciones y ajustes que puse como revisión en este PR (es lo que ya estuvimos hablando)
- [ ] Como la idea es no incorporar, a priori, esta funcionalidad a clientes actuales (por lo menos no automáticamente al actualizar el repo por, posiblemente, alguna otra cuestión), entonces:.. Acá te iba a poner que usemos que se active mediante una configuración el item de menú para exportar, pero como es medio lío explicar de última veo si lo agrego yo, no hay problema.

Sobre los últimos puntos que pusiste/resumiste el único que no estoy seguro es el 2 ya que no solo interesa aplicada vs sufrida si no tmb que retención en sí es (IIBB y provincia, drei, iva, ganancias, etc). Igualmente, si te sigue pareciendo conveniente probamos, agrega todo esos menús en proc. períódico y vemos (probablemente luego de aceptar el PR lo haga activable desde la config para que por defecto no se les active al resto)

2016-10-26 02:25 UTC, ivantodorovich commented
Dale, me parece perfecto!

Mañana hago esos cambios y los pusheo, entonces.

Con respecto a lo de ocultar el menú mediante una opción de configuración.. lo que sabría hacer yo es generar un security_group "Manage withholdings" y asignarselo al menú `Procesamiento periódico > Retenciones`. Eso ocultaría todas las nuevas funcionalidades de un sólo saque.
Pero si lo que queres es que se active/desactive desde otro lado.. no sabría cómo 😛 


> Sobre los últimos puntos que pusiste/resumiste el único que no estoy seguro es el 2 ya que no solo interesa aplicada vs sufrida si no tmb que retención en sí es (IIBB y provincia, drei, iva, ganancias, etc).

Como yo lo imagino, la primer distinción más importante en retenciones es Aplicada vs Sufrida.
Las sufridas representan un crédito impositivo, mientras que las aplicadas deben ser liquidadas y rendidas a algún ente (AFIP, IIBB, DREI). Dentro de cada menú, se pueden agrupar y filtrar por impuesto, fecha, etc.
La lógica que le encuentro es la misma que la de -supongo- separar las "Facturas de Cliente" de las "Facturas de Proveedor".

2016-10-26 12:51 UTC, jjscarafia commented
Bárbaro, ahí ajusté el primer comentario para tratar de resumir los puntos faltante. Amplio algunos acá para que vayamos viendo:

- Traducciones: recomiendo que por ahora no hagamos la traducción, una vez aceptado el PR se van a sincronizar a transifex, podes traducir ahí y luego las sincronizamos de vuelta al módulo tran (https://www.transifex.com/adhoc/ingadhoc-account-payment-8-0/dashboard/). Te cambié a "reviewer" asi que deberías poder traducir sin problemas. Respecto a las traducciones te recuerdo:
  - Traducir en "es" (no es_AR)
  - Transifex ayuda un poco sugiriendo términos pero es útil tener un odoo abierto e ir buscando términos similares para ver que palabras suelen usarse.
-  Separar modificaciones en módulos: hay un tema, varios campos que utiliza el wizard los crea "l10n_ar_invoice", por lo cual el wizard para generar el archivo lo haría en el módulo "l10n_ar_account_withholding" (hoy vos lo tenés instalado, depende de varios módulos pero seguramente mejoremos la estructura de dependencias para la v9). Dejaría en este PR más que nada lo que tiene que ver con menus, es decir, menú "Procesamiento periódico > Retenciones" y sus hijos "Aplicadas" y "Sufridas"

2016-10-26 12:54 UTC, jjscarafia commented
Tal vez hice un poco de quilombo, espero que se entienda todo.
Saludos!

2016-10-26 14:25 UTC, ivantodorovich commented on account_voucher_withholding/wizard/account_withholding_sicore_wizard.py
> +    company_id = fields.Many2one('res.company', 'Company')
Por si te interesa, acabo de confirmar que los valores seteados desde el menú "Establecer Por Defecto" tienen prioridad sobre cualquier default definido en el módulo. Así que va bárbaro. 👍

2016-10-26 14:55 UTC, ivantodorovich commented
Hice algunas correcciones, según lo hablado, y otras mejoras en la usabilidad del wizard.

Estoy un poco enredado con esto de separar los módulos. Estuve viendo la estructura de dependencias actual, y entiendo lo que decís. Pero tengo las siguientes dudas:
- ¿Cómo pongo la dependencia a este módulo, desde `l10n_ar_account_withholding`, siendo que están en distintos repositorios?
- ¿No generaría algo así como "_dependencias circulares_" (tal vez estoy inventando cosas)?

2016-10-26 15:43 UTC, jjscarafia approved these changes

2016-10-26 15:43 UTC, merged