Mejoras y correcciones del modulo grupo de pagos
ingadhoc/account-payment pull request #205
Opened 2020-08-24 14:43 UTC by klogas

Grupo de Pagos: 
1 - Actualizar el monto de la línea del pago cuando se cambia la moneda del diario.
2 - Cuando se genera el pago desde la vista de facturas traer solo la deuda de las facturas y no la deuda global del cliente.
3 - Cuando se seleccionen varias facturas desde la vista de factura y se marque la opción "Registrar Pagos" que redireccione a grupo de pagos y no al pago estándar de Odoo.
4 - Modificar algunas traducciones del módulo.

2020-08-28 01:11 UTC, jjscarafia reviewed
Buenas! Gracias por el PR. 
Dejo algunos comentarios

2020-08-28 01:11 UTC, jjscarafia commented on account_check/i18n/es_AR.po
> +# Translation of Odoo Server.
no debería haber archivo es_ar, solo con el es.po es suficiente

2020-08-28 01:11 UTC, jjscarafia commented on account_check/models/account_check.py
> +    check_subtype = fields.Selection(
porque este campo acá y no related? es para la funcionalidad de poder crear cheques a mano?

2020-08-28 01:11 UTC, jjscarafia commented on account_check/models/account_check.py
> +        string='Issue Date',
por alguna razón se agregan todos los "strings"? No tengo problemas de agregarlos, pero si son cambios innecesarios mejor evitarlos para minimizar el diff y facilitar review

2020-08-28 01:11 UTC, jjscarafia commented on account_check/models/account_check.py
> +        move = self.env['account.move'].with_context(default_type='entry').create(payment._prepare_payment_moves())
en que caso es necesario este default_type entry? les trajo algun inconvenienite? solo para poder replicar y entender el cambio

2020-08-28 01:11 UTC, jjscarafia commented on account_check/models/account_checkbook.py
> +    check_subtype = fields.Selection(
el cambio del nombre del campo es por claridad nomás?

2020-08-28 01:11 UTC, jjscarafia commented on account_payment_group/i18n/es.po
> +#. module: account_payment_group
Todo lo que es traducciones mejor hacerlo en transfiex porque es más facil el review, 
por esta vez que ya está hecho lo podríamos dejar acá, pero para la próxima es mejor ir por ese camino https://www.transifex.com/adhoc/ingadhoc-account-payment-13-0/dashboard/

2020-08-28 02:30 UTC, klogas commented on account_check/i18n/es_AR.po
> +# Translation of Odoo Server.
Se eliminara el fichero es_AR

2020-08-28 02:32 UTC, klogas commented on account_check/models/account_check.py
> +    check_subtype = fields.Selection(
No puede ser un campo related ya que la idea es utilizar el subtipo de cheque tanto para los cheques propios como cheques de tercero. Una funcionalidad que nos han solicitado todos nuestros clientes. En este caso para emplearlo en los cheques de tercero como no tengo chequera se debe establecer de forma manual y no puede ser un campo related.

2020-08-28 02:33 UTC, klogas commented on account_check/models/account_check.py
> +        string='Issue Date',
No son necesarios se van a eliminar eliminados.

2020-08-28 02:35 UTC, klogas commented on account_check/models/account_check.py
> +        move = self.env['account.move'].with_context(default_type='entry').create(payment._prepare_payment_moves())
Si en este caso nos daba un error al crear el asiento, donde nos pedía algunos datos de factura, por lo que se especifico que fuera un asiento contable y no nos diera ese problema.

2020-08-28 02:36 UTC, klogas commented on account_check/models/account_checkbook.py
> +    check_subtype = fields.Selection(
Realmente se cambio ya que se desea utilizar el subtipo de cheque tanto para cheques de tercero y propio, y el nombre entonces infería que solo se emplea en el cheque propio lo cual puede crear confusión.

2020-08-28 02:38 UTC, klogas commented on account_payment_group/i18n/es.po
> +#. module: account_payment_group
Entendido en otras traducciones la realizaremos por aca.

2020-09-01 11:27 UTC, klogas commented on account_payment_group/i18n/es.po
> +#. module: account_payment_group
Se solicito acceso al en transifex para traducir el repo ingadhoc-account-payment-13-0 y también al ingadhoc-odoo-argentina-13-0 que estaremos subiendo algunas mejoras en estos días. En este ultimo tuve que solicitar portugués porque no me deja añadirme al español puedes revisar esto.

2020-09-11 01:52 UTC, jjscarafia requested changes
Buenas, gracias nuevamente por el PR
Ahí dejé algunos comentarios nuevos. Para ir avanzando hice un merge parcial de las cosas sobre las cuales no tenía duda.

Para poder continuar con este PR deberían hacer un rebase (seguramente va a dar varios conflictos) o un merge a origin/13.0. El merge se resuelve rápido, solo un conflicto simple donde dejan sus cambios. 

Cualquier duda me dicen

2020-09-11 01:52 UTC, jjscarafia commented on account_check/models/account_check.py
> +    check_subtype = fields.Selection(
Buenas! respecto a esto todavía no estoy convencido y el cambio es un poco fuerte.
Lo que solemos hacer para identificar cheques de terceros diferidos vs corrientes es que no pongan fecha de vencimiento en el cheque.
Por otro lado, los cheques de terceros electrónicos los solemos identificar con un diario distinto, "Cheques de terceros electrónicos", de hecho creo que si tenés en distintos bancos te conviene uno para cada banco.

2020-09-11 01:52 UTC, jjscarafia commented on account_check/models/account_check.py
> +                rec.bank_id = rec.journal_id.bank_id
Entiendo que esto es para que quede el dato del banco en el cheque propio, pero más que hacerlo por acá, no lo podríamos hacer en el momento del create del cheque? es como más robusto. O sea, que cada vez que se cree vaya a crear un cheque propio se cree con el bank de ese journal.

2020-09-11 01:52 UTC, jjscarafia commented on account_check/models/account_check.py
> +    def onchange_amount(self):
si no me equivoco está mejora es para cualquier pago, no solo de cheques. Por lo cual creo que la mandaria a account_payment_fix o account_payment_group. Te parece?

2020-09-11 01:52 UTC, jjscarafia commented on account_payment_group/models/account_payment_group.py
> +            rec.unmatched_amount_company = rec.currency_id._convert(rec.unmatched_amount, rec.company_currency_id, rec.company_id,
Este campo no parece estar creado en ningún lugar o estoy equivocado?

2020-09-11 01:52 UTC, jjscarafia commented on account_check/models/account_check.py
> +    check_subtype = fields.Selection(
por las dudas, no digo que no, simplemente que querría terminarme de convencer de que es necesario y que es el mejor approach. En cheques de tercero todavía no le veo la ventaja de usar este campo

2020-09-11 01:52 UTC, jjscarafia commented on account_payment_group/models/account_payment_group.py
> +            # Cuando se genera el pago desde la factura debe reconocer las deudas de las
Con [este fix de acá](https://github.com/ingadhoc/account-payment/blob/13.0/account_payment_group/models/account_payment_group.py#L463) ya no debería hacer falta todo este cambio y queda como está en v11/v12.

Cuestión, probar con versión más reciente, yo creo que todo esto no debería hacer falta

2020-09-21 14:26 UTC, klogas commented on account_check/models/account_check.py
> +    def onchange_amount(self):
Hola Juan esto es solo para cheques pero como ustedes no crean cheques desde el menú de cheques no lo necesitan ahí lo elimino.

2020-09-21 14:27 UTC, klogas commented on account_check/models/account_check.py
> +                rec.bank_id = rec.journal_id.bank_id
Ok lo paso para el create de cheques.

2020-09-21 14:30 UTC, klogas commented on account_payment_group/models/account_payment_group.py
> +            rec.unmatched_amount_company = rec.currency_id._convert(rec.unmatched_amount, rec.company_currency_id, rec.company_id,
Hola Juan ese campo fue un error de uno de nuestros desarrolladores que subió a una rama equivocada pero yo le dije que lo quitara y ya esta arriba el cambio. De todos modos me fijo que no este para el otro commit.

2020-09-21 14:45 UTC, klogas commented on account_payment_group/models/account_payment_group.py
> +            # Cuando se genera el pago desde la factura debe reconocer las deudas de las
Hola Juan ahi chequeo y si me sale bien elimino lo que te subi.

2020-09-21 14:47 UTC, klogas commented on account_check/models/account_check.py
> +    check_subtype = fields.Selection(
Hola juan la verdad es que otro diría por el cual conciliar sera mas inconveniente por eso los clientes solicitan que estén en el mismo diario y solo especificar que sea electrónico. Si te preocupa el nombre dejamos el nombre actual pero que se pueda utilizar tanto en cheque propios como de tercero?

2020-09-21 21:25 UTC, klogas commented on account_payment_group/models/account_payment_group.py
> +            # Cuando se genera el pago desde la factura debe reconocer las deudas de las
Hola juan en esta parte si lo dejamos así como refieres cuando una partner tiene varias facturas abiertas y selecciono a pagar solo 2 me trae todas las facturas y no solo la deuda seleccionada. Esto ya lo probé en varias ocasiones y tuve que hacer esta modificación para que solo cuando selecciono varias facturas me permitiera pagar solo la deuda que tenían las facturas seleccionadas y no toda la deuda del partner.

2020-09-21 22:42 UTC, klogas commented
Hola Juan acabo de hacer un commit con los siguientes cambios:
1 - Restablecí el nombre del campo check_subtype a issue_check_subtype.
2 - Elimine método onchange_amount que para ustedes no es necesario porque solo crean cheques desde el pago.
3 - Elimine el método onchange_journal_id y redefine el create como indicas.
4 - Elimine campo innecesario unmatched_amount_company. 

Estaré atenta a tus comentarios. Saludos

2022-01-27 18:16 UTC, jjscarafia commented
@klogas cierro esto que nos quedó super viejo. lamento que no pudimos llegar a tiempo para mezclar

2022-01-27 18:16 UTC, closed without merging

2022-01-27 18:17 UTC, roboadhoc commented
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

2022-01-27 18:17 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/205).