[MIG] card_installment: Migration to 17.0
ingadhoc/account-payment pull request #425
Opened 2023-12-04 18:28 UTC by rov-adhoc

2023-12-04 18:28 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/425).

2023-12-12 11:43 UTC, maq-adhoc requested changes
@rov-adhoc, fijate que podemos sacar unos string que no son necesarios y verificar si no podemos hacer el company check auto del modelo

2023-12-12 11:43 UTC, maq-adhoc commented on card_installment/models/account_card.py
> -        string='company',
- Este string no es necesario borrar
- evaluaría usar en la definicion del modelo    
    _check_company_auto = True
     y si el modelo de instalment tiene compania tambien agregar
    _check_company_domain = models.check_company_domain_parent_of

2023-12-12 11:43 UTC, maq-adhoc commented on card_installment/models/account_card_installment.py
> +        string='Coefficient',
- Este string no es necesario

2023-12-12 11:43 UTC, maq-adhoc commented on card_installment/models/account_card_installment.py
> +        string='Bank Discount',
- Este string no es necesario borrar

2023-12-12 11:43 UTC, maq-adhoc commented on card_installment/views/card_installment_view.xml
> +</odoo>
Falta un enter al final del archivo

2023-12-12 13:31 UTC, maq-adhoc approved these changes

2023-12-13 14:30 UTC, jjscarafia commented
@roboadhoc r+

2023-12-13 14:39 UTC, closed without merging