[ADD] account_payment: add kanban
ingadhoc/account-payment pull request #447
Opened 2024-02-02 20:54 UTC by rov-adhoc

2024-02-02 20:55 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/447).

2024-02-09 12:21 UTC, maq-adhoc requested changes

2024-02-09 12:21 UTC, maq-adhoc commented on account_payment_group/views/account_payment_group_view.xml
> +    <field name="view_mode">tree,form,graph,kanban</field>
@rov-adhoc Ro entiendo que aqui y en la otra accion no tenes que agregar el kanban

2024-02-09 12:21 UTC, maq-adhoc commented on account_payment_group/views/account_payment_group_view.xml
> +    <field name="view_mode">tree,form,graph,kanban</field>
Aqui tampoco

2024-02-09 12:22 UTC, jjscarafia commented on account_payment_group/models/account_payment_group.py
> +    _inherit = ['mail.thread','mail.activity.mixin']
con el cambio que propone filo probablemente no sea necesario heredar activities

2024-02-09 13:43 UTC, maq-adhoc requested changes

2024-02-09 13:43 UTC, maq-adhoc commented on account_payment_group/views/account_payment_view.xml
> +        <field name="view_mode">tree,form,graph,kanban</field>
@rov-adhoc  tampoco pondría la vista kanban para las transferencias puede ser peligroso. Agrega una funcionalidad que no necesitamos

2024-02-09 16:10 UTC, rov-adhoc commented on account_payment_group/views/account_payment_view.xml
> +        <field name="view_mode">tree,form,graph,kanban</field>
@maq-adhoc listo!! gracias FIlo!

2024-02-09 20:25 UTC, maq-adhoc commented
@roboadhoc r+

2024-02-09 20:29 UTC, closed without merging