[ADD] account_cashbox_l10n_latam_check: modify the
ingadhoc/account-payment pull request #461
Opened 2024-02-26 19:13 UTC by rov-adhoc

view_l10n_latam_payment_mass_transfer_form in order to add permission to account.group_account_invoice

2024-02-26 19:14 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/461).

2024-02-26 20:17 UTC, maq-adhoc requested changes

2024-02-26 20:17 UTC, maq-adhoc commented on account_cashbox_l10n_latam_check/views/account_payment_view.xml
> +                <button name="%(l10n_latam_check.action_view_l10n_latam_payment_mass_transfer)d" type="action" string="Check Transfer" groups="account.group_account_invoice"/>
@rov-adhoc 
No es necesario cambiar todo el botón ya que solo cambiamos un atributo

algo tipo 

```xml
<button name="%(l10n_latam_check.action_view_l10n_latam_payment_mass_transfer)d"  position="attributes">
    <attribute name="groups">account.group_account_invoice</attribute>
</button>
```

Incluso no recuerdo si funcionaba en los grupos pero algo asi para no perder grupos que se pudieron modificar en otra vista
```xml
<button name="%(l10n_latam_check.action_view_l10n_latam_payment_mass_transfer)d"  position="attributes">
<attribute name="groups" add=",account.group_account_invoice" />
   </button>
```
Por otro lado dejaría por las dudas el grupo original (los grupos podes dividirlos con coma)

2024-02-26 20:17 UTC, maq-adhoc commented on account_cashbox_l10n_latam_check/i18n/es.po
> +
Si solo modificamos el atributo, no debería ser necesario actualizar la traducción en el modulo

2024-02-26 20:27 UTC, rov-adhoc commented on account_cashbox_l10n_latam_check/i18n/es.po
> +
tal cual

2024-02-26 20:27 UTC, rov-adhoc commented on account_cashbox_l10n_latam_check/views/account_payment_view.xml
> +                <button name="%(l10n_latam_check.action_view_l10n_latam_payment_mass_transfer)d" type="action" string="Check Transfer" groups="account.group_account_invoice"/>
perfecto gracias!! @maq-adhoc

2024-02-28 13:54 UTC, maq-adhoc commented
@roboadhoc r+

2024-02-28 13:56 UTC, closed without merging