[FIX] account_cashbox: Fix to avoid the whole debt in account_payment_pro
ingadhoc/account-payment pull request #495
Opened 2024-06-26 15:03 UTC by rov-adhoc

2024-06-26 15:03 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/495).

2024-07-16 10:14 UTC, jjscarafia requested changes

2024-07-16 10:14 UTC, jjscarafia commented on account_payment_pro/models/account_payment.py
> +    @api.depends('payment_type','company_id')
no debería ser necesario repetir "payment_type" (Supongo que ya lo tiene super), los depends entiendo que solo es necesario agregar los nuevos

2024-07-16 10:14 UTC, jjscarafia commented on account_payment_pro/models/account_payment.py
> +        # created_automatically = self._context.get('created_automatically')
esta creo que borrarla automáticamente (y tmb borraría la línea de comentario de arriba)

2024-07-16 19:48 UTC, jjscarafia requested changes

2024-07-16 19:48 UTC, jjscarafia commented on account_cashbox/models/account_payment.py
> +            available_allow_journal = rec.available_journal_ids._origin[:1]
Creo que esto deberia quedar asi
            if rec.journal_id not in rec.available_journal_ids._origin:
                rec.journal_id = available_allow_journal

2024-07-16 19:48 UTC, jjscarafia commented on account_payment_pro/models/account_move.py
> +
enter

2024-07-16 19:48 UTC, jjscarafia commented on account_payment_pro/models/account_payment.py
> +            selected_debt = 0.0
todo esto volvemos como estaba

2024-07-16 19:48 UTC, jjscarafia commented on account_payment_pro/models/account_move_line.py
> +
volverlo a como haciamos antes

default_amount  = abs(sum(to_pay_move_lines.mapped('amount_residual')))

2024-07-18 19:14 UTC, jjscarafia commented
@roboadhoc r+

2024-07-18 19:16 UTC, jjscarafia commented
@roboadhoc rebase-ff

2024-07-18 19:16 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2024-07-18 19:18 UTC, closed without merging