[MIG] account_payment_pro: Migration to 18.0
ingadhoc/account-payment pull request #543
Opened 2024-10-15 19:50 UTC by maq-adhoc

2024-10-15 19:51 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/543).

2024-10-29 16:57 UTC, jjscarafia requested changes

2024-10-29 16:57 UTC, jjscarafia commented on account_payment_pro/models/account_payment.py
> +    @api.depends('move_id.line_ids.matched_debit_ids', 'move_id.line_ids.matched_credit_ids')
en relación a lo que vimos en la capacitación lo haría depender solo de "move_id" o, si no se comporta bien, "move_id.line_ids"

pero evitaría ir profundo...
total es un compute no store

2024-10-29 17:05 UTC, maq-adhoc commented on account_payment_pro/models/account_payment.py
> +    @api.depends('move_id.line_ids.matched_debit_ids', 'move_id.line_ids.matched_credit_ids')
Listo

2024-10-29 18:31 UTC, merged