[DEL] account_payment_pro: Deleted deprecated code in account_payment_pro
ingadhoc/account-payment pull request #546
Opened 2024-10-22 17:55 UTC by rov-adhoc

2024-10-22 17:56 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/546).

2024-10-23 11:20 UTC, maq-adhoc requested changes

2024-10-23 11:20 UTC, maq-adhoc commented on account_payment_pro/models/account_payment.py
>                  raise ValidationError(_('To Pay Amount and Payment Amount must be equal!'))
Creo que Estas dos lineas hay que sacarlas tambien

2024-10-23 11:20 UTC, maq-adhoc commented on account_payment_pro/models/account_payment.py
>              raise UserError(_('Your are trying to modify a protected field on an approved payment. Set it back to edit if you want to make this modification.'))
Creo que estas lineas hay que sacarlas

2024-10-28 13:48 UTC, feg-adhoc commented
@roboadhoc r+

2024-10-28 13:52 UTC, closed without merging